-- PROYECTO FINAL DEL CURSO DE BASE DE DATOS 2020 e
-- MySQL Script generated by MySQL Workbench
-- Sun Aug  9 17:19:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TIENDA_ONLINE_BORRAR
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tienda_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_online` DEFAULT CHARACTER SET utf8 ;
USE `tienda_online` ;

-- -----------------------------------------------------
-- Table `tienda_online`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`administrador` (
  `id_ADMINISTRADOR` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DIRECCION` VARCHAR(45) NOT NULL,
  `TELEFONO` INT NOT NULL,
  `RUC` CHAR(12) NOT NULL,
  `CORREO` VARCHAR(45) NOT NULL,
  `CONTRASEÑA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ADMINISTRADOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`catalogo` (
  `idCATALOGO` INT NOT NULL,
  `Descripción` VARCHAR(45) NOT NULL,
  `tipo_catalogo` TINYBLOB NOT NULL,
  PRIMARY KEY (`idCATALOGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`categorias` (
  `id_CATEGORIAS` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_CATEGORIAS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`estado` (
  `id_ESTADO` INT NOT NULL,
  `NOMBRE_ESTADO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ESTADO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`sistema_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`sistema_pago` (
  `id_SISTEMA_PAGO` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_SISTEMA_PAGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`perfil` (
  `id_PERFIL` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `CONTRASEÑA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_PERFIL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`usuarios` (
  `id_USUARIOS` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `PERFIL_id_PERFIL` INT NOT NULL,
  PRIMARY KEY (`id_USUARIOS`, `PERFIL_id_PERFIL`),
  INDEX `fk_USUARIOS_PERFIL1_idx` (`PERFIL_id_PERFIL` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_PERFIL1`
    FOREIGN KEY (`PERFIL_id_PERFIL`)
    REFERENCES `tienda_online`.`perfil` (`id_PERFIL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`pedido` (
  `id_PEDIDO` INT NOT NULL,
  `FECHA` DATETIME NOT NULL,
  `Departamento_Envio` VARCHAR(45) NOT NULL,
  `Distrito_Envio` VARCHAR(45) NOT NULL,
  `Direccion_Envio` VARCHAR(45) NOT NULL,
  `telefono_Envio` VARCHAR(11) NOT NULL,
  `USUARIOS_id_USUARIOS` INT NOT NULL,
  `SISTEMA_PAGO_id_SISTEMA_PAGO` INT NOT NULL,
  PRIMARY KEY (`id_PEDIDO`, `USUARIOS_id_USUARIOS`, `SISTEMA_PAGO_id_SISTEMA_PAGO`),
  INDEX `fk_ORDEN_USUARIOS1_idx` (`USUARIOS_id_USUARIOS` ASC) VISIBLE,
  INDEX `fk_ORDEN_SISTEMA_PAGO1_idx` (`SISTEMA_PAGO_id_SISTEMA_PAGO` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEN_SISTEMA_PAGO1`
    FOREIGN KEY (`SISTEMA_PAGO_id_SISTEMA_PAGO`)
    REFERENCES `tienda_online`.`sistema_pago` (`id_SISTEMA_PAGO`),
  CONSTRAINT `fk_ORDEN_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_USUARIOS`)
    REFERENCES `tienda_online`.`usuarios` (`id_USUARIOS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`producto` (
  `id_PRODUCTO` INT NOT NULL,
  `NOMBRE` VARCHAR(45) BINARY NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `PRECIO` DECIMAL(10,0) NOT NULL,
  `DESCUENTO` DECIMAL(10,0) NULL,
  `TALLA` VARCHAR(20) NULL DEFAULT NULL,
  `STOCK` INT NULL,
  `CATALOGO_idCATALOGO` INT NOT NULL,
  PRIMARY KEY (`id_PRODUCTO`),
  INDEX `fk_PRODUCTO_CATALOGO1_idx` (`CATALOGO_idCATALOGO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CATALOGO1`
    FOREIGN KEY (`CATALOGO_idCATALOGO`)
    REFERENCES `tienda_online`.`catalogo` (`idCATALOGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`detalle_pedido` (
  `id_DETALLE_PEDIDO` INT NOT NULL,
  `PRODUCTO_NOMBRE` VARCHAR(45) NOT NULL,
  `PRODUCTO_PRECIO` DECIMAL(10,0) NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `FECHA_ENTREGA` DATETIME NOT NULL,
  `PRODUCTO_id_PRODUCTO` INT NOT NULL,
  `PEDIDO_id_PEDIDO` INT NOT NULL,
  `ADMINISTRADOR_id_ADMINISTRADOR` INT NOT NULL,
  `ESTADO_id_ESTADO` INT NOT NULL,
  PRIMARY KEY (`id_DETALLE_PEDIDO`, `PRODUCTO_id_PRODUCTO`, `PEDIDO_id_PEDIDO`, `ADMINISTRADOR_id_ADMINISTRADOR`),
  INDEX `fk_ORDEN_DETALLE_PRODUCTO1_idx` (`PRODUCTO_id_PRODUCTO` ASC) VISIBLE,
  INDEX `fk_ORDEN_DETALLE_PEDIDO1_idx` (`PEDIDO_id_PEDIDO` ASC) VISIBLE,
  INDEX `fk_DETALLE_PEDIDO_ADMINISTRADOR1_idx` (`ADMINISTRADOR_id_ADMINISTRADOR` ASC) VISIBLE,
  INDEX `fk_DETALLE_PEDIDO_ESTADO1_idx` (`ESTADO_id_ESTADO` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_PEDIDO_ADMINISTRADOR1`
    FOREIGN KEY (`ADMINISTRADOR_id_ADMINISTRADOR`)
    REFERENCES `tienda_online`.`administrador` (`id_ADMINISTRADOR`),
  CONSTRAINT `fk_DETALLE_PEDIDO_ESTADO1`
    FOREIGN KEY (`ESTADO_id_ESTADO`)
    REFERENCES `tienda_online`.`estado` (`id_ESTADO`),
  CONSTRAINT `fk_ORDEN_DETALLE_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_PEDIDO`)
    REFERENCES `tienda_online`.`pedido` (`id_PEDIDO`),
  CONSTRAINT `fk_ORDEN_DETALLE_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_PRODUCTO`)
    REFERENCES `tienda_online`.`producto` (`id_PRODUCTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_online`.`producto_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_online`.`producto_has_categorias` (
  `PRODUCTO_id_PRODUCTO` INT NOT NULL,
  `CATEGORIAS_id_CATEGORIAS` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_id_PRODUCTO`, `CATEGORIAS_id_CATEGORIAS`),
  INDEX `fk_PRODUCTO_has_CATEGORIAS_CATEGORIAS1_idx` (`CATEGORIAS_id_CATEGORIAS` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_CATEGORIAS_PRODUCTO1_idx` (`PRODUCTO_id_PRODUCTO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_CATEGORIAS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_id_CATEGORIAS`)
    REFERENCES `tienda_online`.`categorias` (`id_CATEGORIAS`),
  CONSTRAINT `fk_PRODUCTO_has_CATEGORIAS_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_PRODUCTO`)
    REFERENCES `tienda_online`.`producto` (`id_PRODUCTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `tienda_online` ;

-- -----------------------------------------------------
-- procedure ProcedimientoActualizarProductos
-- -----------------------------------------------------

DELIMITER $$
USE `tienda_online`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProcedimientoActualizarProductos`(
in pid_producto int,
in pNombre varchar(45),
in pmarca varchar(45),
in pprecio decimal(10,0),
in ptalla varchar(20),
in pcatalogo_idCATALOGO INT
)
BEGIN
update producto
set 

Nombre=pNombre,
marca=pmarca,
precio=pprecio,
talla=ptalla,
catalogo_idCATALOGO=pcatalogo_idCATALOGO
where
id_producto=pid_producto;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ProcedimientoEliminarProductos
-- -----------------------------------------------------

DELIMITER $$
USE `tienda_online`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProcedimientoEliminarProductos`(
in pid_producto int
)
BEGIN
delete 
from producto
where id_PRODUCTO=pid_producto;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ProcedimientoInsertarProductos
-- -----------------------------------------------------

DELIMITER $$
USE `tienda_online`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProcedimientoInsertarProductos`(
in id_producto int,
in Nombre varchar(45),
in marca varchar(45),
in precio decimal(10,0),
in talla varchar(20),
in catalogo_idCATALOGO INT
)
BEGIN
insert into producto(id_producto,nombre,marca,precio,talla,catalogo_idCATALOGO) 
values(id_producto,nombre,marca,precio,talla,catalogo_idCATALOGO);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
